<?php

namespace app\index\controller;

use think\Controller;
use think\Session;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        define('ID', Session::get('id'));

        if (!session('user.id')) {
            $this->error('用户未登陆', url('user/login'));
        }
    }


}
